services:
  - type: web
    name: sarvesvara-portfolio
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn portfolio_site.wsgi:application"
    releaseCommand: "python manage.py migrate --noinput"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_site.settings
      - key: PYTHON_VERSION
        value: 3.13
